# Generated by Django 6.0.1 on 2026-06-09 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
