# Generated by Django 6.0.7 on 2026-07-25 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_app", "0003_cart_item"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payment",
            name="amount",
            field=models.IntegerField(),
        ),
    ]
