# Generated by Django 6.0.7 on 2026-07-28 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("bon_app", "0004_alter_payment_amount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name="product",
            name="stock",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
