# Generated by Django 5.2.16 on 2026-07-30 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_app', '0005_alter_product_price_alter_product_stock'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='products/'),
        ),
    ]
