# Generated by Django 5.2.16 on 2026-07-31 08:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bon_app', '0006_product_slug_alter_product_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='slug',
        ),
    ]
