# Generated by Django 6.0.7 on 2026-09-22 11:56

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bon_app', '0008_cartitem_delete_cart_item'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='cartitem',
            index=models.Index(fields=['user_cart', 'product'], name='bon_app_car_user_ca_46de36_idx'),
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['name', 'id'], name='bon_app_pro_name_bbe25c_idx'),
        ),
    ]
